import { useState } from "react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader } from "../components/ui/card";
import { FormField } from "../components/ui/form-field";
import { Input } from "../components/ui/input";
import { removeBrandingImage, updateBarangayProfile, updateBrandingImage, type ProfileInput } from "../services/barangay-profile-service";
import type { BarangayProfileSummary } from "../types/barangay";

export function BarangayProfileSettingsPage({ profile, onSaved }: { profile: BarangayProfileSummary; onSaved: (profile: BarangayProfileSummary) => void }) {
  const [form, setForm] = useState<ProfileInput>({ name: profile.name, municipality: profile.municipality, province: profile.province, address: profile.address ?? undefined, contactNumber: profile.contactNumber ?? undefined, email: profile.email ?? undefined, authorizedSignatory: profile.authorizedSignatory ?? undefined, signatoryPosition: profile.signatoryPosition ?? undefined }); const [message, setMessage] = useState("");
  const save = async () => { try { onSaved(await updateBarangayProfile(form)); setMessage("Barangay profile saved and audit logged."); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const changeImage = async (kind: "logo" | "signature", file?: File) => { if (!file) return; try { onSaved(await updateBrandingImage(kind, { fileName: file.name, mimeType: file.type, bytes: Array.from(new Uint8Array(await file.arrayBuffer())) })); setMessage(`${kind === "logo" ? "Logo" : "Signature"} saved locally.`); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const removeImage = async (kind: "logo" | "signature") => { try { onSaved(await removeBrandingImage(kind)); setMessage(`${kind === "logo" ? "Logo" : "Signature"} removed.`); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  return <div className="mx-auto max-w-4xl"><div className="mb-6"><p className="text-sm font-semibold text-primary">SETTINGS</p><h2 className="mt-1 text-2xl font-bold">Barangay Profile</h2><p className="mt-1 text-sm text-muted-foreground">Changes update application branding throughout the local system.</p></div><Card><CardHeader><h3 className="text-sm font-bold">Barangay information</h3></CardHeader><CardContent><div className="grid grid-cols-2 gap-4"><FormField label="Barangay name" htmlFor="settings-name"><Input id="settings-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></FormField><FormField label="Municipality / City" htmlFor="settings-municipality"><Input id="settings-municipality" value={form.municipality} onChange={(e) => setForm({ ...form, municipality: e.target.value })} /></FormField><FormField label="Province" htmlFor="settings-province"><Input id="settings-province" value={form.province} onChange={(e) => setForm({ ...form, province: e.target.value })} /></FormField><FormField label="Contact number" htmlFor="settings-contact"><Input id="settings-contact" value={form.contactNumber ?? ""} onChange={(e) => setForm({ ...form, contactNumber: e.target.value })} /></FormField><FormField label="Address" htmlFor="settings-address"><Input id="settings-address" value={form.address ?? ""} onChange={(e) => setForm({ ...form, address: e.target.value })} /></FormField><FormField label="Email" htmlFor="settings-email"><Input id="settings-email" value={form.email ?? ""} onChange={(e) => setForm({ ...form, email: e.target.value })} /></FormField><FormField label="Authorized signatory" htmlFor="settings-signatory"><Input id="settings-signatory" value={form.authorizedSignatory ?? ""} onChange={(e) => setForm({ ...form, authorizedSignatory: e.target.value })} /></FormField><FormField label="Signatory position" htmlFor="settings-position"><Input id="settings-position" value={form.signatoryPosition ?? ""} onChange={(e) => setForm({ ...form, signatoryPosition: e.target.value })} /></FormField></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-border pt-5"><ImageControl label="Barangay logo / seal" present={Boolean(profile.logoPath)} onChange={(file) => changeImage("logo", file)} onRemove={() => removeImage("logo")} /><ImageControl label="Authorized signature" present={Boolean(profile.signaturePath)} onChange={(file) => changeImage("signature", file)} onRemove={() => removeImage("signature")} /></div>{message && <p className="mt-4 text-sm text-primary">{message}</p>}<div className="mt-6 flex justify-end"><Button onClick={save}>Save profile</Button></div></CardContent></Card></div>;
}

function ImageControl({ label, present, onChange, onRemove }: { label: string; present: boolean; onChange: (file?: File) => void; onRemove: () => void }) { return <div><p className="text-sm font-semibold">{label}</p><div className="mt-2 flex gap-2"><label className="inline-flex h-9 cursor-pointer items-center rounded-md border border-border bg-white px-3 text-sm font-semibold"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => onChange(event.target.files?.[0])} />{present ? "Replace image" : "Upload image"}</label>{present && <Button variant="secondary" onClick={onRemove}>Remove</Button>}</div><p className="mt-1 text-xs text-muted-foreground">PNG, JPG/JPEG, or WebP · maximum 2 MB</p></div>; }
