import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Save } from "lucide-react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Select } from "../components/ui/select";
import { listAvailableResidents } from "../services/household-service";
import type { Household, HouseholdInput, ResidentOption } from "../types/household";

interface Props { household?: Household; onCancel: () => void; onSave: (input: HouseholdInput) => Promise<void>; }
export function HouseholdForm({ household, onCancel, onSave }: Props) {
  const [addressLine, setAddressLine] = useState(household?.addressLine ?? ""); const [purok, setPurok] = useState(household?.purok ?? ""); const [status, setStatus] = useState<"active" | "inactive">(household?.status ?? "active"); const [headResidentId, setHeadResidentId] = useState(""); const [residents, setResidents] = useState<ResidentOption[]>([]); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!household) void listAvailableResidents().then(setResidents).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, [household]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!addressLine.trim()) { setError("Household address is required."); return; } if (!household && !headResidentId) { setError("Select the household head."); return; } setSaving(true); setError(undefined); try { await onSave({ addressLine, purok, status, headResidentId: headResidentId ? Number(headResidentId) : undefined }); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl space-y-5"><div><Button variant="ghost" size="sm" onClick={onCancel}><ArrowLeft className="size-4" />Households</Button><h1 className="mt-2 text-xl font-semibold">{household ? "Edit household" : "New household"}</h1><p className="text-sm text-muted-foreground">A household is linked to resident records; names are not stored separately.</p></div><form onSubmit={submit} className="space-y-5">{error && <div role="alert" className="rounded-md border border-destructive/30 bg-[#fdebed] px-4 py-3 text-sm text-destructive">{error}</div>}<Card><CardHeader><h2 className="font-semibold">Household information</h2></CardHeader><CardContent className="grid grid-cols-2 gap-5"><div className="col-span-2"><label className="mb-1.5 block text-sm font-medium">Address *</label><Input value={addressLine} placeholder="House no., street, sitio/purok" onChange={(event) => setAddressLine(event.target.value)} required /></div><div><label className="mb-1.5 block text-sm font-medium">Purok / Sitio</label><Input value={purok} onChange={(event) => setPurok(event.target.value)} /></div><div><label className="mb-1.5 block text-sm font-medium">Status</label><Select value={status} onChange={(event) => setStatus(event.target.value as "active" | "inactive")}><option value="active">Active</option><option value="inactive">Inactive</option></Select></div>{!household && <div className="col-span-2"><label className="mb-1.5 block text-sm font-medium">Household head *</label><Select value={headResidentId} onChange={(event) => setHeadResidentId(event.target.value)}><option value="">Select an available resident</option>{residents.map((resident) => <option key={resident.id} value={resident.id}>{resident.fullName} · {resident.residentCode}</option>)}</Select>{!residents.length && <p className="mt-2 text-xs text-muted-foreground">There are no active residents available for assignment.</p>}</div>}</CardContent></Card><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={saving}><Save className="size-4" />{saving ? "Saving…" : "Save household"}</Button></div></form></div>;
}
