import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Archive, ChevronLeft, ChevronRight, Eye, Plus, Search, Pencil } from "lucide-react";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Select } from "../components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../components/ui/table";
import { hasPermission } from "../hooks/use-permission";
import { archiveResident, createResident, getResidentProfile, listResidents, updateResident } from "../services/resident-service";
import type { SessionUser } from "../types/auth";
import type { Resident, ResidentInput, ResidentListQuery, ResidentProfile, ResidentStatus } from "../types/resident";
import { ResidentForm } from "./ResidentForm";

interface Props { user: SessionUser; initialResidentId?: number; onInitialResidentOpened?: () => void; }
type View = { kind: "list" } | { kind: "new" } | { kind: "edit"; resident: Resident } | { kind: "profile"; id: number };
const statusVariant: Record<ResidentStatus, "success" | "neutral" | "warning" | "destructive"> = { active: "success", inactive: "neutral", moved_out: "warning", deceased: "destructive" };
const display = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (letter: string) => letter.toUpperCase());
const fullName = (resident: Resident) => [resident.lastName + ",", resident.firstName, resident.middleName, resident.suffix].filter(Boolean).join(" ");
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "—";

function Details({ profile, onBack, onEdit, onArchive, canEdit, canArchive }: { profile: ResidentProfile; onBack: () => void; onEdit: () => void; onArchive: () => void; canEdit: boolean; canArchive: boolean; }) {
  const { resident } = profile;
  return <div className="mx-auto max-w-7xl space-y-5"><div className="flex items-start justify-between"><div><Button variant="ghost" size="sm" onClick={onBack}><ArrowLeft className="size-4" />Residents</Button><div className="mt-2 flex items-center gap-3"><h1 className="text-xl font-semibold">{fullName(resident)}</h1><Badge variant={statusVariant[resident.status]}>{display(resident.status)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Resident ID: {resident.residentCode} · Registered {formatDate(resident.registeredAt)}</p></div><div className="flex gap-2">{canEdit && <Button variant="secondary" onClick={onEdit}><Pencil className="size-4" />Edit</Button>}{canArchive && resident.status === "active" && <Button variant="destructive" onClick={onArchive}><Archive className="size-4" />Archive</Button>}</div></div>
    <div className="grid grid-cols-3 gap-5"><Card className="col-span-2"><CardHeader><h2 className="font-semibold">Personal information</h2></CardHeader><CardContent className="grid grid-cols-3 gap-x-6 gap-y-4 text-sm"><Detail label="First name" value={resident.firstName} /><Detail label="Middle name" value={resident.middleName} /><Detail label="Last name" value={resident.lastName} /><Detail label="Suffix" value={resident.suffix} /><Detail label="Date of birth" value={formatDate(resident.birthDate)} /><Detail label="Sex" value={display(resident.sex)} /><Detail label="Civil status" value={resident.civilStatus} /><Detail label="Nationality" value={resident.nationality} /><Detail label="Occupation" value={resident.occupation} /></CardContent></Card>
      <Card><CardHeader><h2 className="font-semibold">Contact</h2></CardHeader><CardContent className="space-y-4 text-sm"><Detail label="Contact number" value={resident.contactNumber} /><Detail label="Email address" value={resident.email} /></CardContent></Card>
      <Card className="col-span-2"><CardHeader><h2 className="font-semibold">Residence</h2></CardHeader><CardContent className="grid grid-cols-2 gap-x-6 gap-y-4 text-sm"><Detail label="Address" value={resident.address} /><Detail label="Barangay" value={resident.barangay} /><Detail label="Municipality / City" value={resident.municipality} /><Detail label="Province" value={resident.province} /></CardContent></Card>
      <Card><CardHeader><h2 className="font-semibold">Household</h2></CardHeader><CardContent className="text-sm">{profile.household ? <div className="space-y-2"><p className="font-medium">{profile.household.householdCode}</p><p>{profile.household.addressLine}</p><p className="text-muted-foreground">{profile.household.isHouseholdHead ? "Household head" : profile.household.relationshipToHead}{profile.household.purok ? ` · ${profile.household.purok}` : ""}</p></div> : <p className="text-muted-foreground">No household assignment recorded.</p>}</CardContent></Card>
      <Card className="col-span-2"><CardHeader><h2 className="font-semibold">Documents</h2></CardHeader><CardContent>{profile.documents.length ? <div className="space-y-3 text-sm">{profile.documents.map((document) => <div className="flex items-center justify-between" key={document.documentNumber}><div><p className="font-medium">{document.documentType}</p><p className="text-muted-foreground">{document.documentNumber} · {formatDate(document.issuedAt)}</p></div><Badge variant={document.status === "issued" ? "success" : "neutral"}>{display(document.status)}</Badge></div>)}</div> : <p className="text-sm text-muted-foreground">No documents have been issued.</p>}</CardContent></Card>
      <Card><CardHeader><h2 className="font-semibold">Activity</h2></CardHeader><CardContent>{profile.activity.length ? <div className="space-y-3 text-sm">{profile.activity.map((activity, index) => <div key={`${activity.action}-${index}`}><p className="font-medium">{display(activity.action)}</p><p className="text-muted-foreground">{formatDate(activity.createdAt)}{activity.userName ? ` · ${activity.userName}` : ""}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No activity recorded.</p>}</CardContent></Card>
    </div></div>;
}
function Detail({ label, value }: { label: string; value: string | null }) { return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-foreground">{value || "—"}</p></div>; }

export function ResidentsPage({ user, initialResidentId, onInitialResidentOpened }: Props) {
  const [view, setView] = useState<View>({ kind: "list" });
  const [result, setResult] = useState<{ records: Resident[]; total: number }>({ records: [], total: 0 });
  const [profile, setProfile] = useState<ResidentProfile>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>();
  const [search, setSearch] = useState(""); const [status, setStatus] = useState<ResidentListQuery["status"]>("all"); const [sex, setSex] = useState<ResidentListQuery["sex"]>("all"); const [page, setPage] = useState(1); const [sortBy, setSortBy] = useState<ResidentListQuery["sortBy"]>("lastName"); const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");
  const pageSize = 15;
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { setResult(await listResidents({ search, status, sex, page, pageSize, sortBy, sortDirection })); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setLoading(false); } }, [search, status, sex, page, sortBy, sortDirection]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 200); return () => window.clearTimeout(timer); }, [load]);
  const showProfile = async (id: number) => { setLoading(true); setError(undefined); try { setProfile(await getResidentProfile(id)); setView({ kind: "profile", id }); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setLoading(false); } };
  useEffect(() => { if (initialResidentId) { void showProfile(initialResidentId); onInitialResidentOpened?.(); } }, [initialResidentId]);
  const afterSave = async (input: ResidentInput, existing?: Resident) => { const resident = existing ? await updateResident(existing.id, input) : await createResident(input); await load(); await showProfile(resident.id); };
  const doArchive = async () => { if (!profile || !window.confirm(`Archive ${fullName(profile.resident)}? This keeps the historical record and removes it from active status.`)) return; try { await archiveResident(profile.resident.id); await load(); setView({ kind: "list" }); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const canCreate = hasPermission(user, "residents.create"), canEdit = hasPermission(user, "residents.edit"), canArchive = hasPermission(user, "residents.archive");
  if (view.kind === "new") return <ResidentForm onCancel={() => setView({ kind: "list" })} onSave={afterSave} />;
  if (view.kind === "edit") return <ResidentForm resident={view.resident} onCancel={() => view.resident && void showProfile(view.resident.id)} onSave={(input) => afterSave(input, view.resident)} />;
  if (view.kind === "profile") { if (loading || !profile) return <div className="grid min-h-64 place-items-center text-sm text-muted-foreground">Loading resident record…</div>; return <Details profile={profile} onBack={() => setView({ kind: "list" })} onEdit={() => setView({ kind: "edit", resident: profile.resident })} onArchive={() => void doArchive()} canEdit={canEdit} canArchive={canArchive} />; }
  const pages = Math.max(1, Math.ceil(result.total / pageSize));
  return <div className="mx-auto max-w-7xl space-y-5"><div className="flex items-end justify-between"><div><h1 className="text-xl font-semibold">Residents</h1><p className="mt-1 text-sm text-muted-foreground">Maintain the barangay’s resident registry and historical records.</p></div>{canCreate && <Button onClick={() => setView({ kind: "new" })}><Plus className="size-4" />New resident</Button>}</div>
    {error && <div role="alert" className="rounded-md border border-destructive/30 bg-[#fdebed] px-4 py-3 text-sm text-destructive">{error}</div>}
    <Card><CardContent className="flex items-center gap-3 py-4"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={search} placeholder="Search by resident ID or name…" onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></div><Select className="w-36" value={status} onChange={(e) => { setStatus(e.target.value as ResidentListQuery["status"]); setPage(1); }}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="moved_out">Moved out</option><option value="deceased">Deceased</option></Select><Select className="w-36" value={sex} onChange={(e) => { setSex(e.target.value as ResidentListQuery["sex"]); setPage(1); }}><option value="all">All sexes</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option><option value="unspecified">Not specified</option></Select><Select className="w-40" value={`${sortBy}:${sortDirection}`} onChange={(e) => { const [field, direction] = e.target.value.split(":"); setSortBy(field as ResidentListQuery["sortBy"]); setSortDirection(direction as "asc" | "desc"); }}><option value="lastName:asc">Name, A–Z</option><option value="lastName:desc">Name, Z–A</option><option value="registeredAt:desc">Newest registered</option><option value="registeredAt:asc">Oldest registered</option></Select></CardContent></Card>
    <Card><Table><TableHeader><TableRow><TableHead>Resident</TableHead><TableHead>Resident ID</TableHead><TableHead>Sex</TableHead><TableHead>Contact</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{loading ? <TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">Loading residents…</TableCell></TableRow> : result.records.length ? result.records.map((resident) => <TableRow key={resident.id}><TableCell><button className="font-semibold text-primary hover:underline" onClick={() => void showProfile(resident.id)}>{fullName(resident)}</button><p className="mt-1 text-xs text-muted-foreground">{resident.barangay || resident.address || "Address not recorded"}</p></TableCell><TableCell className="font-mono text-xs">{resident.residentCode}</TableCell><TableCell>{display(resident.sex)}</TableCell><TableCell>{resident.contactNumber || resident.email || "—"}</TableCell><TableCell><Badge variant={statusVariant[resident.status]}>{display(resident.status)}</Badge></TableCell><TableCell><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" title="View resident" onClick={() => void showProfile(resident.id)}><Eye className="size-4" /></Button>{canEdit && <Button size="icon" variant="ghost" title="Edit resident" onClick={() => setView({ kind: "edit", resident })}><Pencil className="size-4" /></Button>}</div></TableCell></TableRow>) : <TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">No resident records match the current filters.</TableCell></TableRow>}</TableBody></Table><div className="flex items-center justify-between border-t border-border px-4 py-3 text-sm text-muted-foreground"><span>{result.total} resident{result.total === 1 ? "" : "s"} · Page {page} of {pages}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft className="size-4" />Previous</Button><Button size="sm" variant="secondary" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Next<ChevronRight className="size-4" /></Button></div></div></Card>
  </div>;
}
