use crate::{database::Database, services::auth_service::{audit, require, Session}};
use rusqlite::params; use serde::{Deserialize, Serialize}; use std::time::{SystemTime, UNIX_EPOCH}; use tauri::State;
#[derive(Serialize)] #[serde(rename_all="camelCase")]
pub struct BlotterCase { pub id:i64,pub case_number:String,pub reported_at:String,pub complainant:String,pub respondent:Option<String>,pub incident_at:Option<String>,pub incident_location:Option<String>,pub incident_description:String,pub action_taken:Option<String>,pub status:String,pub assigned_official_id:Option<i64>,pub assigned_official:Option<String>,pub resolution:Option<String>,pub resolved_at:Option<String>,pub closed_at:Option<String> }
#[derive(Deserialize)] #[serde(rename_all="camelCase")]
pub struct BlotterInput { pub reported_at:Option<String>,pub complainant:String,pub respondent:Option<String>,pub incident_at:Option<String>,pub incident_location:Option<String>,pub incident_description:String,pub action_taken:Option<String>,pub status:String,pub assigned_official_id:Option<i64>,pub resolution:Option<String> }
#[derive(Deserialize)] #[serde(rename_all="camelCase")]
pub struct BlotterQuery { pub search:Option<String>,pub status:Option<String>,pub page:Option<u32>,pub page_size:Option<u32> }
#[derive(Serialize)] #[serde(rename_all="camelCase")]
pub struct BlotterList { pub records:Vec<BlotterCase>,pub total:i64 }
const SELECT:&str="b.id,b.case_number,b.reported_at,b.complainant,b.respondent,b.incident_at,b.incident_location,b.incident_description,b.action_taken,b.status,b.assigned_official_id,u.full_name,b.resolution,b.resolved_at,b.closed_at";
fn optional(value:&Option<String>)->Option<String>{value.as_ref().and_then(|v|(!v.trim().is_empty()).then(||v.trim().to_string()))}
fn read(row:&rusqlite::Row<'_>)->rusqlite::Result<BlotterCase>{Ok(BlotterCase{id:row.get(0)?,case_number:row.get(1)?,reported_at:row.get(2)?,complainant:row.get(3)?,respondent:row.get(4)?,incident_at:row.get(5)?,incident_location:row.get(6)?,incident_description:row.get(7)?,action_taken:row.get(8)?,status:row.get(9)?,assigned_official_id:row.get(10)?,assigned_official:row.get(11)?,resolution:row.get(12)?,resolved_at:row.get(13)?,closed_at:row.get(14)?})}
fn validate(input:&BlotterInput)->Result<(),String>{if input.complainant.trim().is_empty(){return Err("Complainant is required.".into());}if input.incident_description.trim().is_empty(){return Err("Incident description is required.".into());}if !matches!(input.status.as_str(),"open"|"under_investigation"|"resolved"|"closed"|"cancelled"){return Err("Select a valid case status.".into());}if input.status=="resolved"&&optional(&input.resolution).is_none(){return Err("Resolution is required when resolving a case.".into());}Ok(())}
#[tauri::command]
pub fn list_blotter_cases(database:State<'_,Database>,session:State<'_,Session>,query:BlotterQuery)->Result<BlotterList,String>{require(&session,"blotter.view")?;let c=database.connect().map_err(|e|e.to_string())?;let search=query.search.unwrap_or_default().trim().to_string();let like=format!("%{search}%");let status=query.status.unwrap_or_else(||"all".into());let filter="(?1='' OR b.case_number LIKE ?2 OR b.complainant LIKE ?2 OR b.respondent LIKE ?2 OR b.incident_location LIKE ?2) AND (?3='all' OR b.status=?3)";let total:i64=c.query_row(&format!("SELECT COUNT(*) FROM blotter_cases b WHERE {filter}"),params![search,like,status],|r|r.get(0)).map_err(|e|e.to_string())?;let size=query.page_size.unwrap_or(15).clamp(5,100)as i64;let page=query.page.unwrap_or(1).max(1)as i64;let mut s=c.prepare(&format!("SELECT {SELECT} FROM blotter_cases b LEFT JOIN users u ON u.id=b.assigned_official_id WHERE {filter} ORDER BY b.reported_at DESC,b.id DESC LIMIT ?4 OFFSET ?5")).map_err(|e|e.to_string())?;let records=s.query_map(params![search,like,status,size,(page-1)*size],read).map_err(|e|e.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())?;Ok(BlotterList{records,total})}
#[tauri::command]
pub fn get_blotter_case(database:State<'_,Database>,session:State<'_,Session>,case_id:i64)->Result<BlotterCase,String>{require(&session,"blotter.view")?;let c=database.connect().map_err(|e|e.to_string())?;c.query_row(&format!("SELECT {SELECT} FROM blotter_cases b LEFT JOIN users u ON u.id=b.assigned_official_id WHERE b.id=?1"),[case_id],read).map_err(|e|e.to_string())}
#[tauri::command]
pub fn create_blotter_case(database:State<'_,Database>,session:State<'_,Session>,input:BlotterInput)->Result<BlotterCase,String>{let actor=require(&session,"blotter.create")?;validate(&input)?;let c=database.connect().map_err(|e|e.to_string())?;let seed=SystemTime::now().duration_since(UNIX_EPOCH).map_err(|_|"System clock unavailable.")?.as_millis();c.execute("INSERT INTO blotter_cases(case_number,reported_at,complainant,respondent,incident_at,incident_location,incident_description,action_taken,status,assigned_official_id,resolution,resolved_at,closed_at) VALUES(?1,COALESCE(?2,CURRENT_TIMESTAMP),?3,?4,?5,?6,?7,?8,?9,?10,?11,CASE WHEN ?9='resolved' THEN CURRENT_TIMESTAMP END,CASE WHEN ?9='closed' THEN CURRENT_TIMESTAMP END)",params![format!("TEMP-{seed}"),optional(&input.reported_at),input.complainant.trim(),optional(&input.respondent),optional(&input.incident_at),optional(&input.incident_location),input.incident_description.trim(),optional(&input.action_taken),input.status,input.assigned_official_id,optional(&input.resolution)]).map_err(|e|e.to_string())?;let id=c.last_insert_rowid();let year:String=c.query_row("SELECT strftime('%Y','now')",[],|r|r.get(0)).map_err(|e|e.to_string())?;c.execute("UPDATE blotter_cases SET case_number=?1 WHERE id=?2",params![format!("BLT-{year}-{id:06}"),id]).map_err(|e|e.to_string())?;audit(&c,Some(actor.id),"blotter_case_created","blotter_case",Some(id));get_case(&c,id)}
fn get_case(c:&rusqlite::Connection,id:i64)->Result<BlotterCase,String>{c.query_row(&format!("SELECT {SELECT} FROM blotter_cases b LEFT JOIN users u ON u.id=b.assigned_official_id WHERE b.id=?1"),[id],read).map_err(|e|e.to_string())}
#[tauri::command]
pub fn update_blotter_case(database:State<'_,Database>,session:State<'_,Session>,case_id:i64,input:BlotterInput)->Result<BlotterCase,String>{let actor=require(&session,"blotter.edit")?;validate(&input)?;let c=database.connect().map_err(|e|e.to_string())?;get_case(&c,case_id)?;c.execute("UPDATE blotter_cases SET reported_at=COALESCE(?1,reported_at),complainant=?2,respondent=?3,incident_at=?4,incident_location=?5,incident_description=?6,action_taken=?7,status=?8,assigned_official_id=?9,resolution=?10,resolved_at=CASE WHEN ?8='resolved' THEN COALESCE(resolved_at,CURRENT_TIMESTAMP) ELSE resolved_at END,closed_at=CASE WHEN ?8='closed' THEN COALESCE(closed_at,CURRENT_TIMESTAMP) ELSE closed_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?11",params![optional(&input.reported_at),input.complainant.trim(),optional(&input.respondent),optional(&input.incident_at),optional(&input.incident_location),input.incident_description.trim(),optional(&input.action_taken),input.status,input.assigned_official_id,optional(&input.resolution),case_id]).map_err(|e|e.to_string())?;audit(&c,Some(actor.id),"blotter_case_updated","blotter_case",Some(case_id));get_case(&c,case_id)}
