use crate::{database::Database, services::auth_service::{audit, require, Session}};
use rusqlite::{params, OptionalExtension};
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::State;

const DEFAULT_TYPES: &[(&str, &str)] = &[("barangay-clearance", "Barangay Clearance"), ("certificate-of-residency", "Certificate of Residency"), ("certificate-of-indigency", "Certificate of Indigency"), ("certificate-of-good-moral-character", "Certificate of Good Moral Character"), ("certificate-of-no-income", "Certificate of No Income"), ("business-clearance", "Business Clearance"), ("other", "Other")];
#[derive(Serialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentType { pub id: i64, pub code: String, pub name: String, pub description: Option<String>, pub status: String }
#[derive(Deserialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentTypeInput { pub name: String, pub description: Option<String>, pub status: String }
#[derive(Serialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentRequest { pub id: i64, pub request_code: String, pub resident_id: i64, pub resident_name: String, pub resident_code: String, pub document_type_id: i64, pub document_type: String, pub purpose: String, pub status: String, pub requested_at: String, pub requested_by: Option<String>, pub approved_by: Option<String>, pub released_by: Option<String>, pub released_at: Option<String>, pub rejection_reason: Option<String> }
#[derive(Deserialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentRequestInput { pub resident_id: i64, pub document_type_id: i64, pub purpose: String }
#[derive(Deserialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentRequestQuery { pub search: Option<String>, pub status: Option<String>, pub document_type_id: Option<i64>, pub date: Option<String>, pub page: Option<u32>, pub page_size: Option<u32> }
#[derive(Serialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentRequestList { pub records: Vec<DocumentRequest>, pub total: i64 }
#[derive(Deserialize)] #[serde(rename_all = "camelCase")]
pub struct StatusInput { pub status: String, pub rejection_reason: Option<String> }
#[derive(Serialize)] #[serde(rename_all = "camelCase")]
pub struct DocumentResidentOption { pub id: i64, pub resident_code: String, pub full_name: String }
#[derive(Serialize)] #[serde(rename_all = "camelCase")]
pub struct CertificateData { pub document_number: String, pub verification_token: String, pub resident_name: String, pub document_type: String, pub purpose: String, pub issued_at: String, pub barangay_name: String, pub municipality: String, pub province: String, pub address: Option<String>, pub authorized_signatory: Option<String>, pub signatory_position: Option<String> }

pub fn seed_document_types(database: &Database) -> Result<(), String> { let connection = database.connect().map_err(|error| error.to_string())?; for (code, name) in DEFAULT_TYPES { connection.execute("INSERT OR IGNORE INTO document_types(code,name,status) VALUES(?1,?2,'active')", params![code, name]).map_err(|error| error.to_string())?; } Ok(()) }
fn optional(value: &Option<String>) -> Option<String> { value.as_ref().and_then(|text| (!text.trim().is_empty()).then(|| text.trim().to_string())) }
fn slug(value: &str) -> String { let output: String = value.to_lowercase().chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '-' }).collect(); output.trim_matches('-').split('-').filter(|p| !p.is_empty()).collect::<Vec<_>>().join("-") }
fn read_type(row: &rusqlite::Row<'_>) -> rusqlite::Result<DocumentType> { Ok(DocumentType { id: row.get(0)?, code: row.get(1)?, name: row.get(2)?, description: row.get(3)?, status: row.get(4)? }) }
fn read_request(row: &rusqlite::Row<'_>) -> rusqlite::Result<DocumentRequest> { Ok(DocumentRequest { id: row.get(0)?, request_code: row.get(1)?, resident_id: row.get(2)?, resident_name: row.get(3)?, resident_code: row.get(4)?, document_type_id: row.get(5)?, document_type: row.get(6)?, purpose: row.get(7)?, status: row.get(8)?, requested_at: row.get(9)?, requested_by: row.get(10)?, approved_by: row.get(11)?, released_by: row.get(12)?, released_at: row.get(13)?, rejection_reason: row.get(14)? }) }
const REQUEST_SELECT: &str = "dr.id,dr.request_code,dr.resident_id,trim(r.first_name || ' ' || coalesce(r.middle_name || ' ', '') || r.last_name || coalesce(' ' || r.suffix, '')),r.resident_code,dr.document_type_id,dt.name,dr.purpose,dr.status,dr.requested_at,requester.full_name,approver.full_name,releaser.full_name,dr.released_at,dr.rejection_reason";

#[tauri::command]
pub fn list_document_types(database: State<'_, Database>, session: State<'_, Session>, include_inactive: Option<bool>) -> Result<Vec<DocumentType>, String> { require(&session, "documents.view")?; let connection = database.connect().map_err(|error| error.to_string())?; let sql = if include_inactive.unwrap_or(false) { "SELECT id,code,name,description,status FROM document_types ORDER BY name" } else { "SELECT id,code,name,description,status FROM document_types WHERE status='active' ORDER BY name" }; let mut statement = connection.prepare(sql).map_err(|error| error.to_string())?; let values = statement.query_map([], read_type).map_err(|error| error.to_string())?.collect::<Result<Vec<_>, _>>().map_err(|error| error.to_string())?; Ok(values) }
#[tauri::command]
pub fn list_document_residents(database: State<'_, Database>, session: State<'_, Session>) -> Result<Vec<DocumentResidentOption>, String> { require(&session, "documents.create")?; let connection=database.connect().map_err(|error|error.to_string())?; let mut statement=connection.prepare("SELECT id,resident_code,trim(first_name || ' ' || coalesce(middle_name || ' ', '') || last_name || coalesce(' ' || suffix, '')) FROM residents WHERE status='active' ORDER BY last_name,first_name LIMIT 500").map_err(|error|error.to_string())?; let values=statement.query_map([],|row|Ok(DocumentResidentOption{id:row.get(0)?,resident_code:row.get(1)?,full_name:row.get(2)?})).map_err(|error|error.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|error|error.to_string())?;Ok(values) }
#[tauri::command]
pub fn create_document_type(database: State<'_, Database>, session: State<'_, Session>, input: DocumentTypeInput) -> Result<DocumentType, String> { let actor = require(&session, "settings.edit")?; if input.name.trim().is_empty() { return Err("Document type name is required.".into()); } if !matches!(input.status.as_str(), "active" | "inactive") { return Err("Select a valid status.".into()); } let code = slug(&input.name); if code.is_empty() { return Err("Document type name must contain letters or numbers.".into()); } let connection = database.connect().map_err(|error| error.to_string())?; connection.execute("INSERT INTO document_types(code,name,description,status) VALUES(?1,?2,?3,?4)", params![code, input.name.trim(), optional(&input.description), input.status]).map_err(|_| "A document type with this name already exists.".to_string())?; let id = connection.last_insert_rowid(); audit(&connection, Some(actor.id), "document_type_created", "document_type", Some(id)); connection.query_row("SELECT id,code,name,description,status FROM document_types WHERE id=?1", [id], read_type).map_err(|error| error.to_string()) }
#[tauri::command]
pub fn update_document_type(database: State<'_, Database>, session: State<'_, Session>, document_type_id: i64, input: DocumentTypeInput) -> Result<DocumentType, String> { let actor = require(&session, "settings.edit")?; if input.name.trim().is_empty() || !matches!(input.status.as_str(), "active" | "inactive") { return Err("Enter a document type name and valid status.".into()); } let connection = database.connect().map_err(|error| error.to_string())?; connection.execute("UPDATE document_types SET name=?1,description=?2,status=?3,updated_at=CURRENT_TIMESTAMP WHERE id=?4", params![input.name.trim(), optional(&input.description), input.status, document_type_id]).map_err(|error| error.to_string())?; audit(&connection, Some(actor.id), "document_type_updated", "document_type", Some(document_type_id)); connection.query_row("SELECT id,code,name,description,status FROM document_types WHERE id=?1", [document_type_id], read_type).map_err(|error| error.to_string()) }
#[tauri::command]
pub fn list_document_requests(database: State<'_, Database>, session: State<'_, Session>, query: DocumentRequestQuery) -> Result<DocumentRequestList, String> { require(&session, "documents.view")?; let connection = database.connect().map_err(|error| error.to_string())?; let search = query.search.unwrap_or_default().trim().to_string(); let filter = format!("%{search}%"); let status = query.status.unwrap_or_else(|| "all".into()); let type_id = query.document_type_id.unwrap_or(0); let date = query.date.unwrap_or_default(); let filters = "(?1='' OR dr.request_code LIKE ?2 OR r.resident_code LIKE ?2 OR r.first_name LIKE ?2 OR r.last_name LIKE ?2) AND (?3='all' OR dr.status=?3) AND (?4=0 OR dr.document_type_id=?4) AND (?5='' OR date(dr.requested_at)=?5)"; let total: i64 = connection.query_row(&format!("SELECT COUNT(*) FROM document_requests dr JOIN residents r ON r.id=dr.resident_id WHERE {filters}"), params![search,filter,status,type_id,date], |row| row.get(0)).map_err(|error| error.to_string())?; let size=query.page_size.unwrap_or(15).clamp(5,100) as i64; let page=query.page.unwrap_or(1).max(1) as i64; let sql=format!("SELECT {REQUEST_SELECT} FROM document_requests dr JOIN residents r ON r.id=dr.resident_id JOIN document_types dt ON dt.id=dr.document_type_id LEFT JOIN users requester ON requester.id=dr.requested_by_user_id LEFT JOIN users approver ON approver.id=dr.approved_by_user_id LEFT JOIN users releaser ON releaser.id=dr.released_by_user_id WHERE {filters} ORDER BY dr.requested_at DESC,dr.id DESC LIMIT ?6 OFFSET ?7"); let mut statement=connection.prepare(&sql).map_err(|error| error.to_string())?; let records=statement.query_map(params![search,filter,status,type_id,date,size,(page-1)*size],read_request).map_err(|error| error.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|error| error.to_string())?; Ok(DocumentRequestList{records,total}) }
#[tauri::command]
pub fn create_document_request(database: State<'_, Database>, session: State<'_, Session>, input: DocumentRequestInput) -> Result<DocumentRequest, String> { let actor=require(&session,"documents.create")?; if input.purpose.trim().is_empty(){return Err("Purpose is required.".into());} let connection=database.connect().map_err(|error|error.to_string())?; let resident: bool=connection.query_row("SELECT EXISTS(SELECT 1 FROM residents WHERE id=?1 AND status='active')",[input.resident_id],|row|row.get(0)).map_err(|error|error.to_string())?; if !resident{return Err("Select an active resident.".into());} let type_active:bool=connection.query_row("SELECT EXISTS(SELECT 1 FROM document_types WHERE id=?1 AND status='active')",[input.document_type_id],|row|row.get(0)).map_err(|error|error.to_string())?;if !type_active{return Err("Select an active document type.".into());}let seed=SystemTime::now().duration_since(UNIX_EPOCH).map_err(|_|"System clock unavailable.")?.as_millis();connection.execute("INSERT INTO document_requests(request_code,resident_id,document_type_id,purpose,status,requested_by_user_id) VALUES(?1,?2,?3,?4,'pending',?5)",params![format!("TEMP-{seed}"),input.resident_id,input.document_type_id,input.purpose.trim(),actor.id]).map_err(|error|error.to_string())?;let id=connection.last_insert_rowid();connection.execute("UPDATE document_requests SET request_code=?1 WHERE id=?2",params![format!("REQ-{id:06}"),id]).map_err(|error|error.to_string())?;audit(&connection,Some(actor.id),"document_request_created","document_request",Some(id));connection.query_row(&format!("SELECT {REQUEST_SELECT} FROM document_requests dr JOIN residents r ON r.id=dr.resident_id JOIN document_types dt ON dt.id=dr.document_type_id LEFT JOIN users requester ON requester.id=dr.requested_by_user_id LEFT JOIN users approver ON approver.id=dr.approved_by_user_id LEFT JOIN users releaser ON releaser.id=dr.released_by_user_id WHERE dr.id=?1"),[id],read_request).map_err(|error|error.to_string()) }
#[tauri::command]
pub fn update_document_request_status(database: State<'_, Database>, session: State<'_, Session>, request_id: i64, input: StatusInput) -> Result<(), String> {
    let permission = match input.status.as_str() { "approved" | "rejected" => "documents.approve", "released" => "documents.release", "cancelled" => "documents.create", _ => return Err("Invalid document request status transition.".into()) };
    let actor = require(&session, permission)?;
    let connection = database.connect().map_err(|error| error.to_string())?;
    let current: Option<String> = connection.query_row("SELECT status FROM document_requests WHERE id=?1", [request_id], |row| row.get(0)).optional().map_err(|error| error.to_string())?;
    let Some(current) = current else { return Err("Document request was not found.".into()); };
    if !matches!((current.as_str(), input.status.as_str()), ("pending", "approved") | ("pending", "rejected") | ("pending", "cancelled") | ("approved", "released") | ("approved", "cancelled")) { return Err("This request cannot be moved to the selected status.".into()); }
    if input.status == "rejected" && optional(&input.rejection_reason).is_none() { return Err("A rejection reason is required.".into()); }
    let result = match input.status.as_str() {
        "approved" => connection.execute("UPDATE document_requests SET status='approved',approved_by_user_id=?1,approved_at=CURRENT_TIMESTAMP,reviewed_by_user_id=?1,reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?2", params![actor.id, request_id]),
        "rejected" => connection.execute("UPDATE document_requests SET status='rejected',approved_by_user_id=?1,approved_at=CURRENT_TIMESTAMP,reviewed_by_user_id=?1,reviewed_at=CURRENT_TIMESTAMP,rejection_reason=?2,updated_at=CURRENT_TIMESTAMP WHERE id=?3", params![actor.id, optional(&input.rejection_reason), request_id]),
        "released" => {
            let type_code: String = connection.query_row("SELECT dt.code FROM document_requests dr JOIN document_types dt ON dt.id=dr.document_type_id WHERE dr.id=?1", [request_id], |row| row.get(0)).map_err(|error| error.to_string())?;
            let year: String = connection.query_row("SELECT strftime('%Y','now')", [], |row| row.get(0)).map_err(|error| error.to_string())?;
            let prefix: String = type_code.split('-').filter_map(|part| part.chars().next()).collect::<String>().to_uppercase();
            let seed = SystemTime::now().duration_since(UNIX_EPOCH).map_err(|_| "System clock unavailable.".to_string())?.as_millis();
            connection.execute("INSERT INTO documents(document_number,document_request_id,resident_id,document_type_id,issued_by_user_id,status,qr_token) SELECT ?1,id,resident_id,document_type_id,?2,'issued',?3 FROM document_requests WHERE id=?4", params![format!("TEMP-{seed}"), actor.id, format!("VER-{request_id}-{seed}"), request_id]).map_err(|error| error.to_string())?;
            let document_id = connection.last_insert_rowid();
            connection.execute("UPDATE documents SET document_number=?1 WHERE id=?2", params![format!("{}-{year}-{document_id:06}", if prefix.is_empty() { "DOC" } else { &prefix }), document_id]).map_err(|error| error.to_string())?;
            connection.execute("UPDATE document_requests SET status='released',released_by_user_id=?1,released_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?2", params![actor.id, request_id])
        },
        _ => connection.execute("UPDATE document_requests SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?1", [request_id]),
    };
    result.map_err(|error| error.to_string())?;
    audit(&connection, Some(actor.id), &format!("document_request_{}", input.status), "document_request", Some(request_id));
    Ok(())
}
#[tauri::command]
pub fn get_certificate_data(database: State<'_, Database>, session: State<'_, Session>, request_id: i64) -> Result<CertificateData, String> {
    require(&session, "documents.view")?;
    let connection = database.connect().map_err(|error| error.to_string())?;
    connection.query_row("SELECT d.document_number,d.qr_token,trim(r.first_name || ' ' || coalesce(r.middle_name || ' ', '') || r.last_name || coalesce(' ' || r.suffix, '')),dt.name,dr.purpose,d.issued_at,b.name,b.municipality,b.province,b.address,b.authorized_signatory,b.signatory_position FROM documents d JOIN document_requests dr ON dr.id=d.document_request_id JOIN residents r ON r.id=d.resident_id JOIN document_types dt ON dt.id=d.document_type_id JOIN barangay_profile b ON 1=1 WHERE d.document_request_id=?1 AND d.status='issued'", [request_id], |row| Ok(CertificateData { document_number: row.get(0)?, verification_token: row.get(1)?, resident_name: row.get(2)?, document_type: row.get(3)?, purpose: row.get(4)?, issued_at: row.get(5)?, barangay_name: row.get(6)?, municipality: row.get(7)?, province: row.get(8)?, address: row.get(9)?, authorized_signatory: row.get(10)?, signatory_position: row.get(11)? })).map_err(|_| "No issued certificate exists for this request.".into())
}
